name: ARM64 Build & Download

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update packages
        run: sudo apt-get update

      - name: Install dependencies & cross toolchain
        run: |
          sudo apt-get install -y alsa-base alsa-utils pkg-config doxygen \
            libasound2-dev libfftw3-dev libgtest-dev libavcodec-dev libavformat-dev \
            libswresample-dev libavfilter-dev libcurl4-openssl-dev libxml++2.6-dev \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - uses: actions/checkout@v3

      - name: Configure CMake (ARM64)
        run: cmake -S . -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++

      - name: Build (ARM64)
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload ARM64 build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spectrum-arm64-build
          path: ${{github.workspace}}/build/
